### ISSUE TITLE
mytardis_url endpoint is sensitive to trailing slash

### ISSUE THREAD

**Issue by pansapiens** [monash-merc/mydata#37]
eg, in the settings dialog, for the "MyTardis URL" field,

http://127.0.0.1:8000 is valid (assuming a locally running MyTardis instance)

but with a trailing slash:

http://127.0.0.1:8000/

complains about invalid credentials.

This might be better solved via more forgiving Django routing for the MyTardis API, however MyData could instead choose to strip trailing slashes to catch this type of user error. It's an unlikely case, given the way the software will usually be deployed, but I stumbled upon it during development when copy-pasting the URL from the browser to the settings dialog.

**Comment by wettenhj** [comment]
Thanks for reporting this.

The error I get in this case is a 404 (Not Found), rather than a complaint about "invalid credentials":

![mydatamytardis404](https://cloud.githubusercontent.com/assets/2209245/7037141/fd9832e2-dde0-11e4-8bb8-b0b8da1c2695.PNG)

Yes, MyData could strip trailing slashes - which would seem more like a "workaround" than a "solution".   As you say, it's really more of an issue with Django's routing in the MyTardis test server.  If I can't think of a better workaround, I'd be happy to implement the trailing slash stripping in MyData.
