### ISSUE TITLE
Mac menu bar focus problem

### ISSUE THREAD

**Issue by sharynys** [monash-merc/mydata#69]
When a MyData window is already open, clicking the icon in Mac menu bar doesn't bring it to foreground and menu options are greyed out. Can get around this but it's irritating... Any plans to fix?

**Comment by wettenhj** [comment]
Thanks for reporting this, @sharynys

The short answer is unfortunately we don't have a nice solution for this, but feel free to contribute one if you find a way to do it.

Presumably this is when MyData's Settings dialog is open?  It's a modal dialog, which is why MyData's menu items are disabled.  We could consider changing it to a non-modal dialog, but such a change would require careful thought and thorough testing, and I'm not sure if it's worth it.

We could make MyData a regular application which would always appear in the Dock, then it would be easier to switch back to it after using other applications.  But we want encourage users to leave MyData running in the background, so that it can respond to scheduled tasks etc. so it needs to be unobtrusive.

We certainly understand the desire to be able to use MyData's system tray menu to reactivate the MyData application and place it in front of other application windows.  But at the moment we can only provide a "best effort" approach to this, due to some tricky issues with window managers and events.  We do frequently use MyData's system tray menu to open MyData's main window (or settings dialog) when no MyData windows area already open.  But if you are returning to an open MyData window after using another application, you might need to drag the other application's window aside or minimize it, rather than trying to use MyData's menu to bring MyData to the front.

Issues with system tray menus can be OS-specific, and we tend to prioritize Windows, because it is used on most instrument PCs which MyData is installed on.

**Comment by sharynys** [comment]
I understand, James, thanks! It's more of a mild irritant than a show stopper and will be less of a problem in a production environment I think. Speaking of instrument PCs, what do people do when the instrument PCs run Linux? This seems to be happening more. Does MyData run under Wine? Or do people ingest from the web interface?
